export const CROPS = [
  'apple',
  'banana',
  'blackgram',
  'chickpea',
  'coconut',
  'coffee',
  'cotton',
  'grapes',
  'jute',
  'kidneybeans',
  'lentil',
  'maize',
  'mango',
  'mothbeans',
  'mungbean',
  'muskmelon',
  'orange',
  'papaya',
  'pigeonpeas',
  'pomegranate',
  'rice',
  'watermelon',
] as const;

export type Crop = typeof CROPS[number];

export const CROP_NAMES: Record<Crop, string> = {
  apple: 'Manzana',
  banana: 'Plátano',
  blackgram: 'Frijol Negro',
  chickpea: 'Garbanzo',
  coconut: 'Coco',
  coffee: 'Café',
  cotton: 'Algodón',
  grapes: 'Uvas',
  jute: 'Yute',
  kidneybeans: 'Frijol Rojo',
  lentil: 'Lenteja',
  maize: 'Maíz',
  mango: 'Mango',
  mothbeans: 'Frijol Polilla',
  mungbean: 'Frijol Mungo',
  muskmelon: 'Melón',
  orange: 'Naranja',
  papaya: 'Papaya',
  pigeonpeas: 'Guandú',
  pomegranate: 'Granada',
  rice: 'Arroz',
  watermelon: 'Sandía',
};

// Mapeo de imágenes de cultivos
export const CROP_IMAGES: Record<Crop, any> = {
  apple: require('../assets/images/crops/manzana.jpg'),
  banana: require('../assets/images/crops/platano.jpg'),
  blackgram: require('../assets/images/crops/frijol_negro.jpg'),
  chickpea: require('../assets/images/crops/garbanzo.jpg'),
  coconut: require('../assets/images/crops/coco.jpg'),
  coffee: require('../assets/images/crops/cafe.jpg'),
  cotton: require('../assets/images/crops/algodon.jpg'),
  grapes: require('../assets/images/crops/uvas.jpg'),
  jute: require('../assets/images/crops/yute.jpg'),
  kidneybeans: require('../assets/images/crops/frijol_rojo.jpg'),
  lentil: require('../assets/images/crops/lenteja.jpg'),
  maize: require('../assets/images/crops/maiz.jpg'),
  mango: require('../assets/images/crops/mango.jpg'),
  // Para los cultivos sin imagen, usamos una imagen por defecto
  mothbeans: require('../assets/images/crops/frijol_negro.jpg'),
  mungbean: require('../assets/images/crops/frijol_negro.jpg'),
  muskmelon: require('../assets/images/crops/platano.jpg'),
  orange: require('../assets/images/crops/mango.jpg'),
  papaya: require('../assets/images/crops/platano.jpg'),
  pigeonpeas: require('../assets/images/crops/garbanzo.jpg'),
  pomegranate: require('../assets/images/crops/mango.jpg'),
  rice: require('../assets/images/crops/maiz.jpg'),
  watermelon: require('../assets/images/crops/platano.jpg'),
};
